# Site Info
title: "Emojist"
info:
  short: "Emojis and their entries"
  long: "Emojist is the only site where you can find an open-sourced list with all the emojis that are currently available and their entries."

# Author Info
author:
  name: "Nil Vila"
  website: "http://desinil.ga"
  twitter: "desinil"
  dribbble: "nvila"
  github: "nil"

baseurl: ""
port: 1515

links:
  github: "http://github.com/nil/emojist"
  ph: "#"

share:
  twitter: "#"
  facebook: "https://www.facebook.com/sharer/sharer.php?u=http%3A//emojist.tk"

# Build settings
markdown: kramdown
sass:
  style: compressed

#Collections
collections:
  - emojis
