# Site settings
title: Emojist

baseurl: ""
url: "http://yourdomain.com"
port: 1515

github_username:  nil
twitter_username: desinil
twitter-share: "https://twitter.com/home?status=%F0%9F%98%B1%20HTML%20and%20Hexadecimal%20codes%20for%20all%20the%20emojis!%20%F0%9F%91%80%F0%9F%91%89%20http%3A//emojist.ml"

# Build settings
markdown: kramdown
sass:
  style: compressed

#Collections
collections:
  - emojis
  - faces
