# Site Info
title: "Emojentry"
info:
  short: "Emojis and their entries"
  long: "Emojentry is the only site where you can find an open-sourced list with all the emojis that are currently available and their entries."

# Author Info
author:
  name: "Nil Vila"
  website: "http://desinil.ga"
  twitter: "desinil"
  dribbble: "nvila"
  github: "nil"

baseurl: ""
port: 1515

links:
  github: "http://github.com/emojentry/emojentry"
  ph: "https://www.producthunt.com/tech/emojist-2"

share:
  twitter: "https://twitter.com/home?status=%F0%9F%93%A3%20The%20easiest%20way%20to%20know%20the%20entries%20of%20any%20emoji%20is%20using%20Emojentry!%20%F0%9F%98%B1%20Check%20it%20on%20http%3A//emojentry.tk%20%F0%9F%91%88%F0%9F%91%80"
  facebook: "https://www.facebook.com/sharer/sharer.php?u=http%3A//emojist.tk"

# Build settings
markdown: kramdown
sass:
  style: compressed

#Collections
collections:
  - emojis
